/**
 * Recordings Routes — CRUD for automation recordings
 * Stored as JSON in PostgreSQL (simple, no separate actions table)
 */

const express = require('express');
const { query } = require('../db');
const { authMiddleware, apiKeyMiddleware } = require('../middleware/auth');

const router = express.Router();

/**
 * POST /api/recordings — Save a recording (from extension, API key auth)
 */
router.post('/', apiKeyMiddleware, async (req, res) => {
  try {
    const { id, name, actions, startUrl, createdAt, actionCount } = req.body;

    await query(
      `INSERT INTO recordings (ext_id, name, actions, start_url, action_count, created_at)
       VALUES ($1, $2, $3, $4, $5, $6)
       ON CONFLICT (ext_id) DO UPDATE SET
         name = EXCLUDED.name,
         actions = EXCLUDED.actions,
         action_count = EXCLUDED.action_count`,
      [id, name, JSON.stringify(actions), startUrl, actionCount, createdAt || new Date().toISOString()]
    );

    res.json({ ok: true });
  } catch (err) {
    console.error('[Recordings] Save error:', err.message);
    res.status(500).json({ error: 'Failed to save recording' });
  }
});

/**
 * GET /api/recordings — List all recordings (dashboard, JWT auth)
 */
router.get('/', authMiddleware, async (req, res) => {
  try {
    const result = await query(
      `SELECT id, ext_id, name, action_count, start_url, created_at
       FROM recordings ORDER BY created_at DESC`
    );
    res.json(result.rows);
  } catch (err) {
    console.error('[Recordings] List error:', err.message);
    res.status(500).json({ error: 'Failed to list recordings' });
  }
});

/**
 * GET /api/recordings/:id — Get full recording with actions
 */
router.get('/:id', authMiddleware, async (req, res) => {
  try {
    const result = await query('SELECT * FROM recordings WHERE id = $1', [req.params.id]);
    if (result.rows.length === 0) return res.status(404).json({ error: 'Not found' });
    const rec = result.rows[0];
    rec.actions = typeof rec.actions === 'string' ? JSON.parse(rec.actions) : rec.actions;
    res.json(rec);
  } catch (err) {
    console.error('[Recordings] Get error:', err.message);
    res.status(500).json({ error: 'Failed to get recording' });
  }
});

/**
 * DELETE /api/recordings/:id — Delete a recording
 */
router.delete('/:id', authMiddleware, async (req, res) => {
  try {
    await query('DELETE FROM recordings WHERE id = $1', [req.params.id]);
    res.json({ ok: true });
  } catch (err) {
    console.error('[Recordings] Delete error:', err.message);
    res.status(500).json({ error: 'Failed to delete recording' });
  }
});

/**
 * DELETE /api/recordings — Delete all recordings
 */
router.delete('/', authMiddleware, async (req, res) => {
  try {
    await query('DELETE FROM recordings');
    res.json({ ok: true });
  } catch (err) {
    console.error('[Recordings] Clear error:', err.message);
    res.status(500).json({ error: 'Failed to clear recordings' });
  }
});

/**
 * GET /api/recordings/:id/export — Export as Puppeteer script
 */
router.get('/:id/export', authMiddleware, async (req, res) => {
  try {
    const result = await query('SELECT * FROM recordings WHERE id = $1', [req.params.id]);
    if (result.rows.length === 0) return res.status(404).json({ error: 'Not found' });

    const rec = result.rows[0];
    const actions = typeof rec.actions === 'string' ? JSON.parse(rec.actions) : rec.actions;

    const lines = [
      `const puppeteer = require('puppeteer');`,
      ``,
      `// Auto-generated by OmniFetch by BungsuDev`,
      `// Recording: ${rec.name}`,
      `// Created: ${rec.created_at}`,
      `// Actions: ${rec.action_count}`,
      ``,
      `(async () => {`,
      `  const browser = await puppeteer.launch({ headless: false, defaultViewport: null });`,
      `  const page = await browser.newPage();`,
      `  await page.goto('${rec.start_url}', { waitUntil: 'networkidle2' });`,
      ``,
    ];

    for (const action of actions) {
      const delay = Math.max(100, action.delay || 500);
      lines.push(`  await page.waitForTimeout(${delay});`);
      const sel = (action.selector || '').replace(/'/g, "\\'");
      const val = (action.value || '').replace(/'/g, "\\'");

      switch (action.type) {
        case 'click':
          lines.push(`  await page.waitForSelector('${sel}');`);
          lines.push(`  await page.click('${sel}');`);
          break;
        case 'input':
          lines.push(`  await page.waitForSelector('${sel}');`);
          lines.push(`  await page.type('${sel}', '${val}', { delay: 30 });`);
          break;
        case 'select':
          lines.push(`  await page.select('${sel}', '${val}');`);
          break;
        case 'keypress':
          lines.push(`  await page.keyboard.press('${action.key}');`);
          break;
        case 'scroll':
          lines.push(`  await page.evaluate(() => window.scrollTo(${action.scrollX}, ${action.scrollY}));`);
          break;
        case 'submit':
          lines.push(`  await page.$eval('${sel}', f => f.submit());`);
          break;
        case 'navigate':
          lines.push(`  await page.goto('${action.url}', { waitUntil: 'networkidle2' });`);
          break;
      }
      lines.push('');
    }

    lines.push(`  console.log('✅ Done!');`);
    lines.push(`  // await browser.close();`);
    lines.push(`})();`);

    const filename = `${rec.name.replace(/[^a-z0-9]/gi, '_')}_puppeteer.js`;
    res.setHeader('Content-Type', 'text/javascript');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(lines.join('\n'));
  } catch (err) {
    console.error('[Recordings] Export error:', err.message);
    res.status(500).json({ error: 'Failed to export recording' });
  }
});

module.exports = router;
